// Generated by gencpp from file wzh_test/pose.msg
// DO NOT EDIT!


#ifndef WZH_TEST_MESSAGE_POSE_H
#define WZH_TEST_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wzh_test
{
template <class ContainerAllocator>
struct pose_
{
  typedef pose_<ContainerAllocator> Type;

  pose_()
    : pose()  {
    }
  pose_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::wzh_test::pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wzh_test::pose_<ContainerAllocator> const> ConstPtr;

}; // struct pose_

typedef ::wzh_test::pose_<std::allocator<void> > pose;

typedef boost::shared_ptr< ::wzh_test::pose > posePtr;
typedef boost::shared_ptr< ::wzh_test::pose const> poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wzh_test::pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wzh_test::pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wzh_test::pose_<ContainerAllocator1> & lhs, const ::wzh_test::pose_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wzh_test::pose_<ContainerAllocator1> & lhs, const ::wzh_test::pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wzh_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wzh_test::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wzh_test::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wzh_test::pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wzh_test::pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wzh_test::pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wzh_test::pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wzh_test::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76249fb45cba333e6a82c7f91cfe1879";
  }

  static const char* value(const ::wzh_test::pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76249fb45cba333eULL;
  static const uint64_t static_value2 = 0x6a82c7f91cfe1879ULL;
};

template<class ContainerAllocator>
struct DataType< ::wzh_test::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wzh_test/pose";
  }

  static const char* value(const ::wzh_test::pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wzh_test::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] pose\n"
;
  }

  static const char* value(const ::wzh_test::pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wzh_test::pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wzh_test::pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wzh_test::pose_<ContainerAllocator>& v)
  {
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WZH_TEST_MESSAGE_POSE_H
